apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj-roselite
  labels:
    app: proj-roselite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proj-roselite
  template:
    metadata:
      name: proj-roselite-pod
      labels:
        app: proj-roselite
    spec:
      containers:
        - name: proj-roselite
          image: echevil/proj-roselite:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: proj-roselite-service
spec:
  selector:
    app: proj-roselite
  ports:
    - name: proj-roselite
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webrtc-ingress
  annotations:
    cert-manager.io/cluster-issuer: "certs-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - webrtc.chenpang.dev
      secretName: webrtc-tls
  rules:
    - host: webrtc.chenpang.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proj-roselite-service
                port:
                  number: 80
