version: "3.8"

services:
  appserver:
    image: node:16.6-bullseye-slim
    environment:
      - NODE_ENV=development
    ports:
      - "8080:3000"
    working_dir: /app
    command: npm run start
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
