version: "3.8"

services:
  appserver:
    build: .
    container_name: appserver
    environment:
      - NODE_ENV=production
    ports:
      - "8080:3000"
    working_dir: /app
    command: npm run start
    restart: unless-stopped
    networks:
      - intern

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./conf/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - appserver
    networks:
      - intern

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email echevil@gmail.com --agree-tos --no-eff-email --staging -d chenpang.dev  -d www.chenpang.dev -d webrtc.chenpang.dev

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  intern:
    driver: bridge