version: "3.8"
services:
  server:
    image: node:16.6-bullseye-slim
    ports:
      - "8080:3001"
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "start"]
    restart: always
    networks:
      - intern
    volumes:
      - type: bind
        source: ./
        target: /app

networks:
  intern:
